# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
theme: jekyll-theme-cayman
title: Brue Land
description: Home of my digital and physical projects. <br/> Check back often to see if I've Brue'd anything new!
email: wesbrueland@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: WesleyBrueland
github_username:  brueland

# Build settings
markdown: kramdown
