# Site settings
theme: jekyll-theme-cayman
title: Brue Land
description: Home of my digital and physical projects. <br/> Check back often to see if I've Brue'd anything new!
email: wesbrueland@gmail.com
baseurl: ""
github_username:  brueland

# Build settings
markdown: kramdown
